name: workflow
on: push

defaults:
  run:
    working-directory: ../../main

jobs:
  unittest:
    if: contains(github.event.head_commit.message, '[CI SKIP]') == false && contains(github.event.head_commit.message, '[CI AUTO]') == false && github.ref == 'refs/heads/master'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Create folder
        working-directory: ../../
        run: mkdir main
      - name: Set up Git SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GIT_SSH }}
      - name: Set up python version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install necessities pip, setuptools, wheel, twine
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Clone 6 repos
        run: |
          git clone ssh://git@github.com/ManderaGeneral/generalimport.git
          git clone ssh://git@github.com/ManderaGeneral/generallibrary.git
          git clone ssh://git@github.com/ManderaGeneral/generalfile.git
          git clone ssh://git@github.com/ManderaGeneral/generalpackager.git
          git clone ssh://git@github.com/Mandera/Mandera.git
          git clone ssh://git@github.com/ManderaGeneral/.github.git
      - name: Install 4 repos
        run: |
          pip install -e generalimport[full]
          pip install -e generallibrary[full]
          pip install -e generalfile[full]
          pip install -e generalpackager[full]
      - name: Run Packager method 'workflow_unittest'
        run: |
          python -c "from generalpackager import Packager; Packager().workflow_unittest()"
        env:
          GH_TOKEN: ${{ secrets.PACKAGER_GITHUB_API }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
  sync:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - name: Create folder
        working-directory: ../../
        run: mkdir main
      - name: Set up Git SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GIT_SSH }}
      - name: Set up python version 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install necessities pip, setuptools, wheel, twine
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Clone 6 repos
        run: |
          git clone ssh://git@github.com/ManderaGeneral/generalimport.git
          git clone ssh://git@github.com/ManderaGeneral/generallibrary.git
          git clone ssh://git@github.com/ManderaGeneral/generalfile.git
          git clone ssh://git@github.com/ManderaGeneral/generalpackager.git
          git clone ssh://git@github.com/Mandera/Mandera.git
          git clone ssh://git@github.com/ManderaGeneral/.github.git
      - name: Install 4 repos
        run: |
          pip install -e generalimport[full]
          pip install -e generallibrary[full]
          pip install -e generalfile[full]
          pip install -e generalpackager[full]
      - name: Run Packager method 'workflow_sync'
        run: |
          python -c "from generalpackager import Packager; Packager().workflow_sync()"
        env:
          GH_TOKEN: ${{ secrets.PACKAGER_GITHUB_API }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
